name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 运行
  workflow_dispatch:      # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Add upstream repository
        run: |
          git remote add upstream ${{ vars.UPSTREAM_REPO || github.repository_owner }}/${{ github.event.repository.name }}
          git fetch upstream
      
      - name: Sync fork
        run: |
          git checkout main
          git merge upstream/main
          git push origin main
