name: Daily Sync with Source Repository

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨 12 点运行
  workflow_dispatch: # 允许手动触发此任务

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 同步源仓库到 Fork 仓库
      - name: Clone source repository
        run: |
          git clone --depth 1 https://github.com/source-org/source-repo.git source-repo

      - name: Push to fork repository
        run: |
          cd source-repo
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add fork https://github.com/your-org/your-repo.git
          git push fork main --force
