name: Daily Sync with Source Repository

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨 12 点运行
  workflow_dispatch: # 允许手动触发此任务

jobs:
  check_and_sync:
    runs-on: ubuntu-latest

    steps:
      # 检查原仓库是否存在
      - name: Check if source repository exists
        id: check_source
        run: |
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" https://github.com/source-org/source-repo)
          if [ "$STATUS" -ne 200 ]; then
            echo "Source repository not found."
            echo "::set-output name=source_exists::false"
            exit 0
          fi
          echo "::set-output name=source_exists::true"

      # 检查是否有更改
      - name: Check for changes in source repository
        if: steps.check_source.outputs.source_exists == 'true'
        id: check_changes
        run: |
          git clone --mirror https://github.com/source-org/source-repo.git source-repo-mirror
          cd source-repo-mirror
          git remote add fork https://github.com/your-org/your-repo.git
          git fetch fork
          if git diff --quiet refs/remotes/origin/main refs/remotes/fork/main; then
            echo "No changes detected. Exiting..."
            echo "::set-output name=has_changes::false"
            exit 0
          fi
          echo "::set-output name=has_changes::true"

      # 如果检测到更改，执行同步
      - name: Sync repository
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone --depth 1 https://github.com/source-org/source-repo.git source-repo
          cd source-repo
          git remote add fork https://github.com/your-org/your-repo.git
          git push fork main --force
